---
all:
  children:
    om:
    scm:
    datanodes:
  vars:
     install_base: /opt/hadoop
     java_home: /usr/java/latest
     ozone_tarball: ozone-0.5.0-SNAPSHOT.tar.gz

om:
  hosts:
    n001.hdfs.example.com:

scm:
  hosts:
    n002.hdfs.example.com:

datanodes:
  hosts:
    n001.hdfs.example.com:
    n002.hdfs.example.com:
    n003.hdfs.example.com:
