---
all:
  children:
    om:
    scm:
    datanodes:

om:
  hosts:
    n001.hdfs.example.com:

scm:
  hosts:
    n002.hdfs.example.com:

datanodes:
  hosts:
    n001.hdfs.example.com:
    n002.hdfs.example.com:
    n003.hdfs.example.com:

s3gateways:
  hosts:
    n001.hdfs.example.com:
    n002.hdfs.example.com:
    n003.hdfs.example.com:
