---
 - hosts: all
   remote_user: root

   vars:
     install_base: /opt/hadoop
     extract_dir: "{{ ozone_tarball | basename | regex_replace('(.tar.gz|.tar.bz2|.tar.xz|.tgz|.tar)$', '') }}"
     ozone_home: "{{ install_base }}/{{ extract_dir }}"

   tasks:
   - name: Ensure the hadoop group exists
     group:
      name: hadoop
      state: present

   - name: Ensure the hdfs user exists. The password below is insecure (hdfs).
     user:
       name: "hdfs"
       password: '$6$OD.Syt41QaobNrf6$dAD.HWuFIbLEFqmRBBYm7uF2dbSo/i9MJ7.jMT9Z6aRAOo5PbaDnU7Qv3nOG2AAnUkqXwacznruzq/T8Ywa7g/'
       groups: hadoop   # Empty by default.
       state: present
       shell: /bin/bash       # Defaults to /bin/bash
       system: no             # Defaults to no
       createhome: yes        # Defaults to yes
       home: /home/hdfs       # Defaults to /home/<username>

   - name: Ensure the Ozone install directory exists and is owned by the hdfs user.
     file:
       path: "{{ install_base }}"
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0755

   - name: Ensure directory for datanode.id file exists (ozone.scm.datanode.id.dir)
     file:
       path: /var/hadoop/datanode
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for Datanode storage exists (dfs.datanode.data.dir)
     file:
       path: /data/datanode/data
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for Datanode Ratis Log exists (dfs.container.ratis.datanode.storage.dir)
     file:
       path: /data/datanode/ratis
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for SCM DB exists (ozone.scm.db.dirs)
     file:
       path: /data/scm/db
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for OM DB exists (ozone.om.db.dirs)
     file:
       path: /data/om/db
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for OM Ratis log exists (ozone.om.ratis.storage.dir)
     file:
       path: /data/om/ratis/storage
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Ensure directory for OM Ratis snapshots exists (ozone.om.ratis.snapshot.dir)
     file:
       path: /data/om/ratis/snapshot
       state: directory
       owner: hdfs
       group: hadoop
       mode: 0700

   - name: Extract the Ozone tarball.
     unarchive:
       src: "{{ ozone_tarball }}"
       remote_src: no
       dest: "{{ install_base }}"
       force: yes
       owner: hdfs
       group: hadoop


   - name: Copy ozone-site.xml
     copy:
       src: conf/ozone-site.xml
       dest: "{{ ozone_home }}/etc/hadoop/"
       force: yes
       owner: hdfs
       group: hadoop

